// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

import { resolveMigrationDatabaseUrl } from "./scripts/lib/database-url";

const databaseUrl = resolveMigrationDatabaseUrl();

if (!databaseUrl) {
  console.warn(
    "[prisma.config] 未检测到数据库 URL（DATABASE_URL / POSTGRES_URL 等）。迁移命令将失败。"
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl ?? "postgresql://build-placeholder@127.0.0.1:5432/build",
  },
});
